### ISSUE TITLE
Freezing tests

### ISSUE THREAD

**Issue by HolyPrapor** [vostok/clusterclient.transport#11]
Sometimes all tests pass and become green but test session freezes for some reason

**Comment by kungasc** [comment]
First step: try to enable this tests at GitHub.

**Comment by kungasc** [comment]
https://github.com/vostok/servicediscovery/issues/10

**Comment by HolyPrapor** [comment]
https://github.com/vostok/hosting/issues/54

**Comment by kungasc** [comment]
seems fixed for now
