### ISSUE TITLE
After merging assemblies using ILRepack, transport will not work.

### ISSUE THREAD

**Issue by deniaa** [vostok/clusterclient.transport#2]
1. This method load assemblies from resources. All this assemblies have type `ITransport`. https://github.com/vostok/clusterclient.transport/blob/master/Vostok.ClusterClient.Transport/TransportFactory.cs#L46
2. After ILRepacking with rename runtime will use interface `XXXITransportXXX`.
3. But ILRepack does not rename interfaces in resources.

This leads to an exception at runtime. When the type `XXXITransportXXX` is required to call methods, we actually loaded the type` ITransport`.

**Comment by iloktionov** [comment]
Fixed in https://github.com/vostok/clusterclient.transport/commit/71e38deb90688264cedcc77fb4e4f89fe5f45461
